version: '3.8'

services:
  # Nginx反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl  # SSL证书目录
    depends_on:
      - backend
      - frontend
    networks:
      - qa_network
    restart: unless-stopped

  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=sqlite:///./data/qa_management.db
      - BACKEND_CORS_ORIGINS=http://localhost,https://localhost
    volumes:
      - backend_data:/app/data
    networks:
      - qa_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - VITE_API_BASE_URL=http://localhost/api
    networks:
      - qa_network
    restart: unless-stopped

  # 数据库备份服务
  backup:
    image: alpine:latest
    volumes:
      - backend_data:/data
      - ./backups:/backups
    command: >
      sh -c "
        while true; do
          echo 'Creating backup...'
          tar -czf /backups/backup_$(date +%Y%m%d_%H%M%S).tar.gz -C /data .
          echo 'Backup created'
          # 保留最近7天的备份
          find /backups -name '*.tar.gz' -mtime +7 -delete
          sleep 86400  # 每24小时备份一次
        done
      "
    networks:
      - qa_network
    restart: unless-stopped

volumes:
  backend_data:

networks:
  qa_network:
    driver: bridge
